name: postcss_transformer
version: 0.1.1
homepage: https://github.com/ajlai/postcss_transformer.dart
author: Anthony Lai <anthonyjlai@gmail.com>
description: Transformer that applies postcss processing.
environment:
    sdk: ">=1.8.0"
dependencies:
  barback: ^0.15.2
dev_dependencies:
  grinder: 0.8.0
  unittest: 0.12.4
  test: 0.12.4+9
  code_transformers: any
